version: 2
jobs:
  build:
  
    working_directory: ~/spring5-recipe-app
    
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      
    steps:
    
      - checkout
      
      - restore_cache:
          key: spring5-recipe-app-{{ checksum "pom.xml" }}
          
      - run: mvn dependency: go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: spring5-recipe-app-{{ checksum "pom.xml" }}
          
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
          
      - store_artifacts:
          path: target/spring5-recipe-app-0.0.1-SNAPSHOT.jar
          
      - run: echo "hello world"
      
